# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  ELBOW_joint:
    has_velocity_limits: false
    max_velocity: 0.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  SHOULDER_joint:
    has_velocity_limits: false
    max_velocity: 0.0
    has_acceleration_limits: false
    max_acceleration: 0
  WRIST_joint:
    has_velocity_limits: false
    max_velocity: 0.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  YAW_joint:
    has_velocity_limits: false
    max_velocity: 0.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  gripper_finger_1_joint_1:
    has_velocity_limits: true
    max_velocity: 100.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  gripper_finger_1_joint_2:
    has_velocity_limits: true
    max_velocity: 100.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  gripper_finger_1_joint_3:
    has_velocity_limits: true
    max_velocity: 100.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  gripper_finger_2_joint_1:
    has_velocity_limits: true
    max_velocity: 100.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  gripper_finger_2_joint_2:
    has_velocity_limits: true
    max_velocity: 100.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  gripper_finger_2_joint_3:
    has_velocity_limits: true
    max_velocity: 100.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  gripper_finger_middle_joint_1:
    has_velocity_limits: true
    max_velocity: 100.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  gripper_finger_middle_joint_2:
    has_velocity_limits: true
    max_velocity: 100.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  gripper_finger_middle_joint_3:
    has_velocity_limits: true
    max_velocity: 100.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  gripper_palm_finger_1_joint:
    has_velocity_limits: true
    max_velocity: 100.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  gripper_palm_finger_2_joint:
    has_velocity_limits: true
    max_velocity: 100.0
    has_acceleration_limits: false
    max_acceleration: 0.0
