# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - qarm_controller
    - gripper_controller

  qarm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - YAW_joint
      - SHOULDER_joint
      - ELBOW_joint
      - WRIST_joint

  gripper_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: false
    joints:
      - gripper_palm_finger_1_joint
      - gripper_palm_finger_2_joint
      - gripper_finger_1_joint_1
      - gripper_finger_1_joint_2
      - gripper_finger_1_joint_3
      - gripper_finger_2_joint_1
      - gripper_finger_2_joint_2
      - gripper_finger_2_joint_3
      - gripper_finger_middle_joint_1
      - gripper_finger_middle_joint_2
      - gripper_finger_middle_joint_3
