# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    manipulator_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

manipulator_controller:
  ros__parameters:
    joints:
      - YAW_joint
      - SHOULDER_joint
      - ELBOW_joint
      - WRIST_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
gripper_controller:
  ros__parameters:
    joints:
      - gripper_palm_finger_1_joint
      - gripper_finger_1_joint_1
      - gripper_finger_1_joint_2
      - gripper_finger_1_joint_3
      - gripper_palm_finger_2_joint
      - gripper_finger_2_joint_1
      - gripper_finger_2_joint_2
      - gripper_finger_2_joint_3
      - gripper_finger_middle_joint_1
      - gripper_finger_middle_joint_2
      - gripper_finger_middle_joint_3
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
