sensors:
  - default_sensor
default_sensor:
  far_clipping_plane_distance: 5.0
  filtered_cloud_topic: /move_group/filtered_cloud
  image_topic: /camera/depth/image_raw
  max_update_rate: 10.0
  near_clipping_plane_distance: 0.3
  padding_offset: 0.01
  padding_scale: 1.0
  queue_size: 5
  sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
  shadow_threshold: 0.2